name: Run Automation Test Project
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - tests/test_driver.py
          - tests/test_api.py

    steps:
      - name: Checkout source code from Github
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          # Cài thêm các thư viện cần thiết cho Chrome và Report
          pip install pytest pytest-html selenium webdriver-manager requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Chrome library
        uses: browser-actions/setup-chrome@latest

      - name: Create a test report Folder
        run: mkdir -p report

      - name: Run Test
        run: pytest ${{matrix.suite}} --maxfail=1 --disable-warnings -q

      - name: Upload file report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report/report.html