name: Run Automation Test Project
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code from Github
        uses: actions/checkout@4

      - name: Install python
        uses: actions/setup-python@5
        with:
          python-version: '3.10'

      - name:  Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome library
        uses: brower-action/setup-chrome@1

      - name: Create a test report Folder
        run: mkdir -p report

      - name: Run Test
        run:  pytest -m smoke --html=report/report.html --seft-contauned-html
      
      - name: Upload file report
        if: always()
        uses: action/upload-actifact@v4
        with:
          name : pytest-report
          path: report/report.html